# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='assets/articulos/')),
                ('tipo', models.CharField(blank=True, choices=[('noticia', 'Noticia'), ('docentes_escolares', 'Servicios Docentes y Escolares'), ('info_academica', 'Información Académica'), ('institucion', 'Institución'), ('extraescolares', 'Actividades Extraescolares')], default='noticia', max_length=20, null=True)),
            ],
        ),
    ]
