# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170419_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('institucion', 'Nuestra Institución'), ('docentes_escolares', 'Servicios Docentes y Escolares'), ('noticia', 'Noticia'), ('extraescolares', 'Actividades Extraescolares'), ('info_academica', 'Información Académica')], default='noticia', max_length=20, null=True),
        ),
    ]
