# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170511_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('docentes_escolares', 'Servicios Docentes y Escolares'), ('info_academica', 'Información Académica'), ('extraescolares', 'Actividades Extraescolares'), ('institucion', 'Nuestra Institución'), ('noticia', 'Noticia')], default='noticia', max_length=20, null=True),
        ),
    ]
