# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=140)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='carreras.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='SubModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('desc', models.TextField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodulos', to='carreras.Modulo')),
            ],
        ),
    ]
