# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/carreras/'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/carreras/modulos/'),
        ),
        migrations.AddField(
            model_name='submodulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/carreras/modulos/'),
        ),
    ]
