# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_remove_carrera_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='imagen',
        ),
    ]
