# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0004_remove_modulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='submodulo',
            name='nombre',
            field=models.CharField(max_length=140),
        ),
    ]
