# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:02
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0006_submodulo_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='cuerpo',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='submodulo',
            name='desc',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
